service: otp-friend

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-2
        
resources:
  Resources:
    otpStoreTableResource:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "otpStore"
        TimeToLiveSpecification:
          AttributeName: expiration_timestamp
          Enabled: true
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "otp_key"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "otp_key"
            KeyType: "HASH"
    OTPLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: otp-lambda-role
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: otp-lambda-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:PutItem
                    - dynamodb:GetItem
                    - dynamodb:UpdateItem
                    - dynamodb:DeleteItem
                    - dynamodb:Query
                    - dynamodb:Scan
                  Resource: 
                    - Fn::GetAtt:
                        - otpStoreTableResource
                        - Arn
                    - Fn::Join:
                      - "/"
                      -
                        - { "Fn::GetAtt": ["otpStoreTableResource", "Arn" ] }
                        - "index/*"
                - Effect: "Allow"
                  Action: 
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource: "arn:aws:logs:*:*:*" 
    ConsumerUser:
      Type: AWS::IAM::User
      Properties:
        UserName: otp-consumer-user
        Policies:
          - PolicyName: otp-consumer-policy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - apigateway:Invoke
                    - apigateway:POST
                    - apigateway:GET
                  Resource: 
                      Fn::Join:
                      - ""
                      - 
                        - "arn:aws:execute-api:"
                        - Ref: "AWS::Region"
                        - ":"
                        - Ref: "AWS::AccountId"
                        - ":"
                        - Ref: "ApiGatewayRestApi"
                        - "/*"
                - Effect: "Allow"
                  Action: 
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource: "arn:aws:logs:*:*:*" 
functions:
  otp-store-lambda:
    handler: otp_handler.save_otp
    environment:
      PYTHONPATH: "./src"
    events:
      - http:
          path: otp
          method: post
          request:
            schemas:
              application/json: ${file(models/model_otp_post.json)}
    role: OTPLambdaRole
  otp-get-lambda:
    handler: otp_handler.get_otp
    environment:
      PYTHONPATH: "./src"
    events:
      - http:
          path: otp/{key}
          method: get
    role: OTPLambdaRole


package:
  patterns:
    - '!test/**'
    - '!target/**'
    - '!.vscode/**'

custom:
  scripts:
    hooks:
      'deploy:finalize': karate/refresh_urls.sh

